# Generated by Django 3.2.5 on 2021-07-20 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_contact_middle_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['last_name']},
        ),
    ]
